"""initial schema

Revision ID: 14d2433d318c
Revises: 
Create Date: 2026-06-26 14:15:08.673120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14d2433d318c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patrons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_number', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patrons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patrons_card_number'), ['card_number'], unique=True)

    op.create_table('works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manifestations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('material_type', sa.String(), nullable=False),
    sa.Column('isbn', sa.String(), nullable=True),
    sa.Column('publisher', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('manifestations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_manifestations_work_id'), ['work_id'], unique=False)

    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manifestation_id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['manifestation_id'], ['manifestations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_barcode'), ['barcode'], unique=True)
        batch_op.create_index(batch_op.f('ix_items_manifestation_id'), ['manifestation_id'], unique=False)

    op.create_table('holds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manifestation_id', sa.Integer(), nullable=False),
    sa.Column('patron_id', sa.Integer(), nullable=False),
    sa.Column('placed_at', sa.DateTime(), nullable=False),
    sa.Column('queue_position', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('assigned_item_id', sa.Integer(), nullable=True),
    sa.Column('pickup_by', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['manifestation_id'], ['manifestations.id'], ),
    sa.ForeignKeyConstraint(['patron_id'], ['patrons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('holds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_holds_assigned_item_id'), ['assigned_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_holds_manifestation_id'), ['manifestation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_holds_patron_id'), ['patron_id'], unique=False)

    op.create_table('loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('patron_id', sa.Integer(), nullable=False),
    sa.Column('loaned_at', sa.DateTime(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('returned_at', sa.DateTime(), nullable=True),
    sa.Column('renewal_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['patron_id'], ['patrons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loans_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_loans_patron_id'), ['patron_id'], unique=False)
        batch_op.create_index('uq_open_loan_per_item', ['item_id'], unique=True, sqlite_where=sa.text('returned_at IS NULL'), postgresql_where=sa.text('returned_at IS NULL'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_index('uq_open_loan_per_item', sqlite_where=sa.text('returned_at IS NULL'), postgresql_where=sa.text('returned_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_loans_patron_id'))
        batch_op.drop_index(batch_op.f('ix_loans_item_id'))

    op.drop_table('loans')
    with op.batch_alter_table('holds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_holds_patron_id'))
        batch_op.drop_index(batch_op.f('ix_holds_manifestation_id'))
        batch_op.drop_index(batch_op.f('ix_holds_assigned_item_id'))

    op.drop_table('holds')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_manifestation_id'))
        batch_op.drop_index(batch_op.f('ix_items_barcode'))

    op.drop_table('items')
    with op.batch_alter_table('manifestations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_manifestations_work_id'))

    op.drop_table('manifestations')
    op.drop_table('works')
    with op.batch_alter_table('patrons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patrons_card_number'))

    op.drop_table('patrons')
    # ### end Alembic commands ###
